# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email